apiVersion: v1
kind: ReplicationController
metadata:
  name: bsg
spec:
  replicas: 2
  selector:
    app: bsgsite
  template:
    metadata:
      labels:
        app: bsgsite
    spec:
      containers:
        - name: git-sync
          image: bonesoul/git-sync
          env:
            - name: "GIT_SYNC_REPO"
              value: "https://github.com/c4po/bonesoul_web.git"
            - name: "GIT_SYNC_WAIT"
              value: "60"
            - name: "GIT_SYNC_DEST"
              value: "/git"
            - name: "GIT_SYNC_BRANCH"
              value: "master"
          volumeMounts:
            - mountPath: /git
              name: gitdata
        - name: hugo
          image: bonesoul/hugo
          volumeMounts:
            - mountPath: /src
              name: gitdata
            - mountPath: /dest
              name: htmldata
        - name: web
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: htmldata
      volumes:
        - name: gitdata
          hostPath:
            path: /gitdata
        - name: htmldata
          hostPath:
            path: /html
---
apiVersion: v1
kind: Service
metadata:
  name: bsg-service
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
  type: "LoadBalancer"
  selector:
    app: bsgsite
